Leaderboard
gursimar03/SCAR pull request #5
Opened 2023-11-12 10:30 UTC by kevashans

- Adjusted Leaderboard design to match Figma design
- Created base navigation structure
- Created base User class design

2023-11-16 09:31 UTC, gursimar03 approved these changes
Good work.

2023-11-17 10:00 UTC, almezj commented on Mobile App/app/src/main/java/com/example/scar/MainScreen.kt
Needs import statement formatting

2023-11-17 10:09 UTC, almezj requested changes

2023-11-17 10:09 UTC, almezj commented on Mobile App/app/src/main/java/com/example/scar/ui/theme/RegionalLeaderboard.kt
Needs import statement formatting

2023-11-17 10:09 UTC, almezj commented on Mobile App/app/src/main/java/com/example/scar/MainScreen.kt
Needs import statement formatting

2023-11-17 10:09 UTC, almezj commented on .idea/modules.xml
Gitignore .idea folder

2023-11-17 10:09 UTC, almezj commented on .idea/vcs.xml
Gitignore .idea folder

2023-11-17 10:09 UTC, almezj commented on .idea/workspace.xml
Gitignore .idea folder

2023-11-20 09:56 UTC, almezj approved these changes

2023-11-20 09:56 UTC, v-philip approved these changes
Good work!

2023-11-20 09:56 UTC, merged